/**
 * External dependencies
 */
import shuffle from 'lodash/shuffle';
import find from 'lodash/find';
import { translate } from 'i18n-calypso';
import { abtest } from 'lib/abtest';

const verticalsV1 = [
	{ value: 'a8c.1', label: translate( 'Arts & Entertainment' ), icon: 'video-camera', stepTwo: [
		{ value: 'a8c.1', label: translate( 'General Arts & Entertainment' ), isGeneral: true },
		{ value: 'a8c.1.3.1', label: translate( 'Creative Arts & Design' ) },
		{ value: 'a8c.1.3.2', label: translate( 'Entertainment & Culture' ) },
		{ value: 'a8c.1.6', label: translate( 'Music' ) },
		{ value: 'a8c.1.5', label: translate( 'Movies' ) },
		{ value: 'a8c.9.23', label: translate( 'Photography' ) },
		{ value: 'a8c.18', label: translate( 'Style & Fashion' ) },
		{ value: 'a8c.17', label: translate( 'Sports & Recreation' ) },
	] },

	{ value: 'a8c.3', label: translate( 'Business & Services' ), icon: 'briefcase', stepTwo: [
		{ value: 'a8c.3', label: translate( 'General Business & Services' ), isGeneral: true },
		{ value: 'a8c.3.0.1', label: translate( 'Finance & Law' ) },
		{ value: 'a8c.3.0.2', label: translate( 'Consulting & Coaching' ) },
		{ value: 'a8c.3.0.3', label: translate( 'Restaurants & Locales' ) },
		{ value: 'a8c.3.1.1', label: translate( 'Advertising & Marketing' ) },
		{ value: 'a8c.2', label: translate( 'Automotive' ) },
		{ value: 'a8c.21', label: translate( 'Real Estate' ) },
		{ value: 'a8c.19', label: translate( 'Technology & Computing' ) },
		{ value: 'a8c.20.18.1', label: translate( 'Hotels & Vacation Rentals' ) },
		{ value: 'a8c.3.0.4', label: translate( 'Communications' ) },
	] },

	{ value: 'a8c.9', label: translate( 'Family, Home, & Lifestyle' ), icon: 'house', stepTwo: [
		{ value: 'a8c.9', label: translate( 'General Family, Home, & Lifestyle' ), isGeneral: true },
		{ value: 'a8c.6', label: translate( 'Family & Parenting' ) },
		{ value: 'a8c.14.7', label: translate( 'Events & Weddings' ) },
		{ value: 'a8c.10', label: translate( 'Home & Garden' ) },
		{ value: 'a8c.8', label: translate( 'Food & Drink' ) },
		{ value: 'a8c.9.2', label: translate( 'DIY & Crafting' ) },
		{ value: 'a8c.20', label: translate( 'Travel' ) },
		{ value: 'a8c.16', label: translate( 'Pets' ) },
	] },

	{ value: 'a8c.5', label: translate( 'Education & Organizations' ), icon: 'institution', stepTwo: [
		{ value: 'a8c.5', label: translate( 'General Education & Organizations' ), isGeneral: true },
		{ value: 'a8c.3.0.6', label: translate( 'Communities & Associations' ) },
		{ value: 'a8c.3.0.5', label: translate( 'Non-Profit' ) },
		{ value: 'a8c.23', label: translate( 'Religion & Spirituality' ) },
		{ value: 'a8c.5.14', label: translate( 'Special Education' ) },
		{ value: 'a8c.5.1', label: translate( 'High School Education' ) },
		{ value: 'a8c.5.5', label: translate( 'College Education' ) },
		{ value: 'a8c.5.10', label: translate( 'Homeschooling' ) },
	] },

	{ value: 'a8c.7', label: translate( 'Health & Wellness' ), icon: 'heart', stepTwo: [
		{ value: 'a8c.7', label: translate( 'General Health & Wellness' ), isGeneral: true },
		{ value: 'a8c.7.37.1', label: translate( 'Mental Health' ) },
		{ value: 'a8c.7.1.1', label: translate( 'Exercise / Weight Loss' ) },
		{ value: 'a8c.7.31', label: translate( 'Men\'s Health' ) },
		{ value: 'a8c.7.45', label: translate( 'Women\'s Health' ) },
		{ value: 'a8c.7.37', label: translate( 'Psychology / Psychiatry' ) },
		{ value: 'a8c.7.32', label: translate( 'Nutrition' ) },
	] },

	{ value: 'a8c.1.1', label: translate( 'Writing & Books' ), icon: 'book', stepTwo: [
		{ value: 'a8c.1.1', label: translate( 'General Writing & Books' ), isGeneral: true },
		{ value: 'a8c.1.1.1', label: translate( 'Book Reviews & Clubs' ) },
		{ value: 'a8c.1.4', label: translate( 'Humor' ) },
		{ value: 'a8c.1.1.2', label: translate( 'Fiction & Poetry' ) },
		{ value: 'a8c.1.1.3', label: translate( 'Author Site' ) },
		{ value: 'a8c.9.28', label: translate( 'Screenwriting' ) },
		{ value: 'a8c.1.1.4', label: translate( 'Non-fiction & Memoir' ) },
	] },
];

const verticalsV2 = [
	{ value: 'a8c.14.7', label: translate( 'Wedding' ) },
	{ value: 'a8c.20', label: translate( 'Travel' ) },
	{ value: 'a8c.1.6', label: translate( 'Music' ) },
	{ value: 'a8c.8', label: translate( 'Food / Drink' ) },
	{ value: 'a8c.9.23', label: translate( 'Photography' ) },
	{ value: 'a8c.3', label: translate( 'Professional Services' ) },
	{ value: 'a8c.6', label: translate( 'Family / Parenting' ) },
	{ value: 'a8c.19', label: translate( 'Technology' ) },
	{ value: 'a8c.0.1', label: translate( 'Personal / Random Thoughts' ) },
	{ value: 'a8c.1', label: translate( 'Art' ) },
	{ value: 'a8c.5', label: translate( 'Education' ) },
	{ value: 'a8c.18', label: translate( 'Fashion / Beauty' ) },
	{ value: 'a8c.0.2', label: translate( 'Lifestyle / Inspiration' ) },
	{ value: 'a8c.7', label: translate( 'Health / Wellness' ) },
	{ value: 'a8c.23', label: translate( 'Religion / Spirituality' ) },
	{ value: 'a8c.17', label: translate( 'Sports / Recreation' ) },
	{ value: 'a8c.11', label: translate( 'Government / Politics' ) },
];

const verticalsOther = [
	{ value: 'a8c.0.1', label: translate( 'Personal Blogging' ) },
	{ value: 'a8c.0.2', label: translate( 'Lifestyle' ) },
	{ value: 'a8c.1', label: translate( 'Arts & Entertainment' ) },
	{ value: 'a8c.1.1', label: translate( 'Books & Literature' ) },
	{ value: 'a8c.1.2', label: translate( 'Celebrity Fan/Gossip' ) },
	{ value: 'a8c.1.3', label: translate( 'Fine Art' ) },
	{ value: 'a8c.1.4', label: translate( 'Humor' ), synonyms: translate( 'Humour' ) },
	{ value: 'a8c.1.5', label: translate( 'Movies' ), synonyms: translate( 'Film, Cinema' ) },
	{ value: 'a8c.1.6', label: translate( 'Music' ) },
	{ value: 'a8c.1.7', label: translate( 'Television' ), synonyms: translate( 'TV' ) },
	{ value: 'a8c.2', label: translate( 'Automotive' ), synonyms: translate( 'Cars' ) },
	{ value: 'a8c.2.1', label: translate( 'Auto Parts' ) },
	{ value: 'a8c.2.2', label: translate( 'Auto Repair' ) },
	{ value: 'a8c.2.3', label: translate( 'Buying/Selling Cars' ) },
	{ value: 'a8c.2.4', label: translate( 'Car Culture' ) },
	{ value: 'a8c.2.5', label: translate( 'Certified Pre-Owned' ) },
	{ value: 'a8c.2.6', label: translate( 'Convertible' ) },
	{ value: 'a8c.2.7', label: translate( 'Coupe' ) },
	{ value: 'a8c.2.8', label: translate( 'Crossover' ) },
	{ value: 'a8c.2.9', label: translate( 'Diesel Vehicles' ) },
	{ value: 'a8c.2.10', label: translate( 'Electric Vehicles' ) },
	{ value: 'a8c.2.11', label: translate( 'Hatchback Vehicles' ) },
	{ value: 'a8c.2.12', label: translate( 'Hybrid Vehicles' ) },
	{ value: 'a8c.2.13', label: translate( 'Luxury Vehicles' ) },
	{ value: 'a8c.2.14', label: translate( 'MiniVan' ) },
	{ value: 'a8c.2.15', label: translate( 'Motorcycles' ), synonyms: translate( 'Motorbikes' ) },
	{ value: 'a8c.2.16', label: translate( 'Off-Road Vehicles' ) },
	{ value: 'a8c.2.17', label: translate( 'Performance Vehicles' ) },
	{ value: 'a8c.2.18', label: translate( 'Pickup Trucks' ) },
	{ value: 'a8c.2.19', label: translate( 'Road-Side Assistance' ) },
	{ value: 'a8c.2.20', label: translate( 'Sedan Vehicles' ) },
	{ value: 'a8c.2.21', label: translate( 'Trucks & Accessories' ) },
	{ value: 'a8c.2.22', label: translate( 'Vintage Cars' ) },
	{ value: 'a8c.2.23', label: translate( 'Wagon Vehicles' ) },
	{ value: 'a8c.3', label: translate( 'Business' ) },
	{ value: 'a8c.3.1', label: translate( 'Advertising' ) },
	{ value: 'a8c.3.2', label: translate( 'Agriculture' ) },
	{ value: 'a8c.3.3', label: translate( 'Biotech/Biomedical' ) },
	{ value: 'a8c.3.4', label: translate( 'Business Software' ) },
	{ value: 'a8c.3.5', label: translate( 'Construction' ) },
	{ value: 'a8c.3.6', label: translate( 'Forestry' ) },
	{ value: 'a8c.3.7', label: translate( 'Government Business' ) },
	{ value: 'a8c.3.8', label: translate( 'Green Solutions' ) },
	{ value: 'a8c.3.9', label: translate( 'Human Resources' ), synonyms: translate( 'HR' ) },
	{ value: 'a8c.3.10', label: translate( 'Logistics' ) },
	{ value: 'a8c.3.11', label: translate( 'Marketing' ) },
	{ value: 'a8c.3.12', label: translate( 'Metallurgy' ) },
	{ value: 'a8c.4', label: translate( 'Careers' ) },
	{ value: 'a8c.4.1', label: translate( 'Career Planning' ) },
	{ value: 'a8c.4.2', label: translate( 'College' ), synonyms: translate( 'University' ) },
	{ value: 'a8c.4.3', label: translate( 'Financial Aid' ) },
	{ value: 'a8c.4.4', label: translate( 'Job Fairs' ) },
	{ value: 'a8c.4.5', label: translate( 'Job Search' ) },
	{ value: 'a8c.4.6', label: translate( 'Resume Writing/Advice' ) },
	{ value: 'a8c.4.7', label: translate( 'Nursing' ) },
	{ value: 'a8c.4.8', label: translate( 'Scholarships' ) },
	{ value: 'a8c.4.9', label: translate( 'Remote Work/Telecommuting' ) },
	{ value: 'a8c.4.10', label: translate( 'U.S. Military' ) },
	{ value: 'a8c.4.11', label: translate( 'Career Advice' ) },
	{ value: 'a8c.5', label: translate( 'Education' ) },
	{ value: 'a8c.5.1', label: translate( '7-12 Education' ) },
	{ value: 'a8c.5.2', label: translate( 'Adult Education' ) },
	{ value: 'a8c.5.3', label: translate( 'Art History' ) },
	{ value: 'a8c.5.4', label: translate( 'Colledge Administration' ) },
	{ value: 'a8c.5.5', label: translate( 'College Life' ) },
	{ value: 'a8c.5.6', label: translate( 'Distance Learning' ) },
	{ value: 'a8c.5.7', label: translate( 'English as a 2nd Language' ) },
	{ value: 'a8c.5.8', label: translate( 'Language Learning' ) },
	{ value: 'a8c.5.9', label: translate( 'Graduate School' ) },
	{ value: 'a8c.5.10', label: translate( 'Homeschooling' ) },
	{ value: 'a8c.5.11', label: translate( 'Homework/Study Tips' ) },
	{ value: 'a8c.5.12', label: translate( 'K-6 Educators' ) },
	{ value: 'a8c.5.13', label: translate( 'Private School' ) },
	{ value: 'a8c.5.14', label: translate( 'Special Education' ) },
	{ value: 'a8c.5.15', label: translate( 'Studying Business' ) },
	{ value: 'a8c.6', label: translate( 'Family & Parenting' ), synonyms: translate( 'Kids' ) },
	{ value: 'a8c.6.1', label: translate( 'Adoption' ) },
	{ value: 'a8c.6.2', label: translate( 'Babies & Toddlers' ) },
	{ value: 'a8c.6.3', label: translate( 'Daycare/Pre School' ) },
	{ value: 'a8c.6.4', label: translate( 'Family Internet' ) },
	{ value: 'a8c.6.5', label: translate( 'Parenting - K-6 Kids' ) },
	{ value: 'a8c.6.6', label: translate( 'Parenting Teens' ) },
	{ value: 'a8c.6.7', label: translate( 'Pregnancy' ) },
	{ value: 'a8c.6.8', label: translate( 'Special Needs Kids' ) },
	{ value: 'a8c.6.9', label: translate( 'Eldercare' ) },
	{ value: 'a8c.7', label: translate( 'Health & Fitness' ) },
	{ value: 'a8c.7.1', label: translate( 'Exercise' ), synonyms: translate( 'Work Out' ) },
	{ value: 'a8c.7.2', label: translate( 'A.D.D.' ), synonyms: translate( 'Attention Deficit Disorder' ) },
	{ value: 'a8c.7.3', label: translate( 'AIDS/HIV' ) },
	{ value: 'a8c.7.4', label: translate( 'Allergies' ) },
	{ value: 'a8c.7.5', label: translate( 'Alternative Medicine' ) },
	{ value: 'a8c.7.6', label: translate( 'Arthritis' ) },
	{ value: 'a8c.7.7', label: translate( 'Asthma' ) },
	{ value: 'a8c.7.8', label: translate( 'Autism/PDD' ) },
	{ value: 'a8c.7.9', label: translate( 'Bipolar Disorder' ) },
	{ value: 'a8c.7.10', label: translate( 'Brain Tumor' ) },
	{ value: 'a8c.7.11', label: translate( 'Cancer' ) },
	{ value: 'a8c.7.12', label: translate( 'Cholesterol' ) },
	{ value: 'a8c.7.13', label: translate( 'Chronic Fatigue Syndrome' ) },
	{ value: 'a8c.7.14', label: translate( 'Chronic Pain' ) },
	{ value: 'a8c.7.15', label: translate( 'Cold & Flu' ) },
	{ value: 'a8c.7.16', label: translate( 'Hearing Loss' ), synonyms: translate( 'Deafness' ) },
	{ value: 'a8c.7.17', label: translate( 'Dental Care' ), synonyms: translate( 'Dentist' ) },
	{ value: 'a8c.7.18', label: translate( 'Depression' ) },
	{ value: 'a8c.7.19', label: translate( 'Dermatology' ), synonyms: translate( 'Skincare' ) },
	{ value: 'a8c.7.20', label: translate( 'Diabetes' ) },
	{ value: 'a8c.7.21', label: translate( 'Epilepsy' ) },
	{ value: 'a8c.7.22', label: translate( 'GERD/Acid Reflux' ) },
	{ value: 'a8c.7.23', label: translate( 'Headaches/Migraines' ) },
	{ value: 'a8c.7.24', label: translate( 'Heart Disease' ) },
	{ value: 'a8c.7.25', label: translate( 'Herbs for Health' ) },
	{ value: 'a8c.7.26', label: translate( 'Holistic Healing' ) },
	{ value: 'a8c.7.27', label: translate( 'IBS/Crohn\'s Disease' ) },
	{ value: 'a8c.7.28', label: translate( 'Incest/Abuse Support' ) },
	{ value: 'a8c.7.29', label: translate( 'Incontinence' ) },
	{ value: 'a8c.7.30', label: translate( 'Infertility' ) },
	{ value: 'a8c.7.31', label: translate( 'Men\'s Health' ) },
	{ value: 'a8c.7.32', label: translate( 'Nutrition' ) },
	{ value: 'a8c.7.33', label: translate( 'Orthopedics' ) },
	{ value: 'a8c.7.34', label: translate( 'Panic/Anxiety Disorders' ) },
	{ value: 'a8c.7.35', label: translate( 'Pediatrics' ) },
	{ value: 'a8c.7.36', label: translate( 'Physical Therapy' ) },
	{ value: 'a8c.7.37', label: translate( 'Psychology/Psychiatry' ) },
	{ value: 'a8c.7.38', label: translate( 'Senor Health' ) },
	{ value: 'a8c.7.39', label: translate( 'Sexuality' ) },
	{ value: 'a8c.7.40', label: translate( 'Sleep Disorders' ) },
	{ value: 'a8c.7.41', label: translate( 'Smoking Cessation' ) },
	{ value: 'a8c.7.42', label: translate( 'Substance Abuse' ) },
	{ value: 'a8c.7.43', label: translate( 'Thyroid Disease' ) },
	{ value: 'a8c.7.44', label: translate( 'Weight Loss' ) },
	{ value: 'a8c.7.45', label: translate( 'Women\'s Health' ) },
	{ value: 'a8c.8', label: translate( 'Food & Drink' ) },
	{ value: 'a8c.8.1', label: translate( 'American Cuisine' ) },
	{ value: 'a8c.8.2', label: translate( 'Barbecues & Grilling' ) },
	{ value: 'a8c.8.3', label: translate( 'Cajun/Creole Cuisine' ) },
	{ value: 'a8c.8.4', label: translate( 'Chinese Cuisine' ) },
	{ value: 'a8c.8.5', label: translate( 'Cocktails/Drinks & Beer' ) },
	{ value: 'a8c.8.6', label: translate( 'Coffee/Tea' ) },
	{ value: 'a8c.8.7', label: translate( 'Cuisine-Specific' ) },
	{ value: 'a8c.8.8', label: translate( 'Desserts & Baking' ) },
	{ value: 'a8c.8.9', label: translate( 'Dining Out' ) },
	{ value: 'a8c.8.10', label: translate( 'Food Allergies' ) },
	{ value: 'a8c.8.11', label: translate( 'French Cuisine' ) },
	{ value: 'a8c.8.12', label: translate( 'Health/Lowfat Cooking' ) },
	{ value: 'a8c.8.13', label: translate( 'Italian Cuisine' ) },
	{ value: 'a8c.8.14', label: translate( 'Japanese Cuisine' ) },
	{ value: 'a8c.8.15', label: translate( 'Mexican Cuisine' ) },
	{ value: 'a8c.8.16', label: translate( 'Vegan' ) },
	{ value: 'a8c.8.17', label: translate( 'Vegetarian' ) },
	{ value: 'a8c.8.18', label: translate( 'Wine' ) },
	{ value: 'a8c.9', label: translate( 'Hobbies & Interests' ) },
	{ value: 'a8c.9.1', label: translate( 'Art/Technology' ) },
	{ value: 'a8c.9.2', label: translate( 'Arts & Crafts' ) },
	{ value: 'a8c.9.3', label: translate( 'Beadwork' ) },
	{ value: 'a8c.9.4', label: translate( 'Birdwatching' ) },
	{ value: 'a8c.9.5', label: translate( 'Board Games/Puzzles' ) },
	{ value: 'a8c.9.6', label: translate( 'Candle & Soap Making' ) },
	{ value: 'a8c.9.7', label: translate( 'Card Games' ) },
	{ value: 'a8c.9.8', label: translate( 'Chess' ) },
	{ value: 'a8c.9.9', label: translate( 'Cigars' ) },
	{ value: 'a8c.9.10', label: translate( 'Collecting' ) },
	{ value: 'a8c.9.11', label: translate( 'Comic Books' ) },
	{ value: 'a8c.9.12', label: translate( 'Drawing/Sketching' ) },
	{ value: 'a8c.9.13', label: translate( 'Freelance Writing' ) },
	{ value: 'a8c.9.14', label: translate( 'Genealogy' ) },
	{ value: 'a8c.9.15', label: translate( 'Getting Published' ) },
	{ value: 'a8c.9.16', label: translate( 'Guitar' ) },
	{ value: 'a8c.9.17', label: translate( 'Home Recording' ) },
	{ value: 'a8c.9.18', label: translate( 'Investors & Patents' ) },
	{ value: 'a8c.9.19', label: translate( 'Jewelry Making' ) },
	{ value: 'a8c.9.20', label: translate( 'Magic & Illusion' ) },
	{ value: 'a8c.9.21', label: translate( 'Needlework' ) },
	{ value: 'a8c.9.22', label: translate( 'Painting' ) },
	{ value: 'a8c.9.23', label: translate( 'Photography' ) },
	{ value: 'a8c.9.24', label: translate( 'Radio' ) },
	{ value: 'a8c.9.25', label: translate( 'Roleplaying Games' ), synonyms: translate( 'RPG' ) },
	{ value: 'a8c.9.26', label: translate( 'Sci-Fi & Fantasy' ) },
	{ value: 'a8c.9.27', label: translate( 'Scrapbooking' ) },
	{ value: 'a8c.9.28', label: translate( 'Screenwriting' ) },
	{ value: 'a8c.9.29', label: translate( 'Stamps & Coins' ) },
	{ value: 'a8c.9.30', label: translate( 'Video & Computer Games' ) },
	{ value: 'a8c.9.31', label: translate( 'Woodworking' ) },
	{ value: 'a8c.10', label: translate( 'Home & Garden' ) },
	{ value: 'a8c.10.1', label: translate( 'Home Appliances' ) },
	{ value: 'a8c.10.2', label: translate( 'Entertaining' ) },
	{ value: 'a8c.10.3', label: translate( 'Environmental Safety' ) },
	{ value: 'a8c.10.4', label: translate( 'Gardening' ) },
	{ value: 'a8c.10.5', label: translate( 'Home Repair' ) },
	{ value: 'a8c.10.6', label: translate( 'Home Theater' ) },
	{ value: 'a8c.10.7', label: translate( 'Interior Decorating' ), synonyms: translate( 'Interior Design' ) },
	{ value: 'a8c.10.8', label: translate( 'Landscaping' ) },
	{ value: 'a8c.10.9', label: translate( 'Remodeling & Construction' ) },
	{ value: 'a8c.11', label: translate( 'Law, Gov\'t & Politics' ) },
	{ value: 'a8c.11.1', label: translate( 'Immigration' ) },
	{ value: 'a8c.11.2', label: translate( 'Legal Issues' ) },
	{ value: 'a8c.11.3', label: translate( 'U.S. Government Resources' ) },
	{ value: 'a8c.11.4', label: translate( 'Politics' ) },
	{ value: 'a8c.11.5', label: translate( 'Commentary' ) },
	{ value: 'a8c.12', label: translate( 'News' ) },
	{ value: 'a8c.12.1', label: translate( 'International News' ) },
	{ value: 'a8c.12.2', label: translate( 'National News' ) },
	{ value: 'a8c.12.3', label: translate( 'Local News' ) },
	{ value: 'a8c.13', label: translate( 'Personal Finance' ) },
	{ value: 'a8c.13.1', label: translate( 'Beginning Investing' ) },
	{ value: 'a8c.13.2', label: translate( 'Credit/Debt & Loans' ) },
	{ value: 'a8c.13.3', label: translate( 'Financial News' ) },
	{ value: 'a8c.13.4', label: translate( 'Financial Planning' ) },
	{ value: 'a8c.13.5', label: translate( 'Hedge Fund' ) },
	{ value: 'a8c.13.6', label: translate( 'Insurance' ) },
	{ value: 'a8c.13.7', label: translate( 'Investing' ) },
	{ value: 'a8c.13.8', label: translate( 'Mutual Funds' ) },
	{ value: 'a8c.13.9', label: translate( 'Options (Investing)' ) },
	{ value: 'a8c.13.10', label: translate( 'Retirement Planning' ) },
	{ value: 'a8c.13.11', label: translate( 'Stocks' ) },
	{ value: 'a8c.13.12', label: translate( 'Tax Planning' ) },
	{ value: 'a8c.14', label: translate( 'Society' ) },
	{ value: 'a8c.14.1', label: translate( 'Dating' ) },
	{ value: 'a8c.14.2', label: translate( 'Divorce Support' ) },
	{ value: 'a8c.14.3', label: translate( 'LGBTQ+' ), synonyms: translate( 'Lesbian, Gay, Bissexual, Transexual, Queer' ) },
	{ value: 'a8c.14.4', label: translate( 'Marriage' ) },
	{ value: 'a8c.14.5', label: translate( 'Senior Living' ) },
	{ value: 'a8c.14.6', label: translate( 'Teens' ) },
	{ value: 'a8c.14.7', label: translate( 'Weddings' ) },
	{ value: 'a8c.14.8', label: translate( 'Ethnic Specific' ) },
	{ value: 'a8c.15', label: translate( 'Science' ) },
	{ value: 'a8c.15.1', label: translate( 'Astrology' ) },
	{ value: 'a8c.15.2', label: translate( 'Biology' ) },
	{ value: 'a8c.15.3', label: translate( 'Chemistry' ) },
	{ value: 'a8c.15.4', label: translate( 'Geology' ) },
	{ value: 'a8c.15.5', label: translate( 'Paranormal Phenomena' ) },
	{ value: 'a8c.15.6', label: translate( 'Physics' ) },
	{ value: 'a8c.15.7', label: translate( 'Space/Astronomy' ) },
	{ value: 'a8c.15.8', label: translate( 'Geography' ) },
	{ value: 'a8c.15.9', label: translate( 'Botany' ) },
	{ value: 'a8c.15.10', label: translate( 'Weather' ) },
	{ value: 'a8c.16', label: translate( 'Pets' ) },
	{ value: 'a8c.16.1', label: translate( 'Aquariums' ) },
	{ value: 'a8c.16.2', label: translate( 'Birds' ) },
	{ value: 'a8c.16.3', label: translate( 'Cats' ) },
	{ value: 'a8c.16.4', label: translate( 'Dogs' ) },
	{ value: 'a8c.16.5', label: translate( 'Large Animals' ) },
	{ value: 'a8c.16.6', label: translate( 'Reptiles' ) },
	{ value: 'a8c.16.7', label: translate( 'Veterinary Medicine' ) },
	{ value: 'a8c.17', label: translate( 'Sports' ) },
	{ value: 'a8c.17.1', label: translate( 'Auto Racing' ) },
	{ value: 'a8c.17.2', label: translate( 'Baseball' ) },
	{ value: 'a8c.17.3', label: translate( 'Bicycling' ) },
	{ value: 'a8c.17.4', label: translate( 'Bodybuilding' ) },
	{ value: 'a8c.17.5', label: translate( 'Boxing' ) },
	{ value: 'a8c.17.6', label: translate( 'Canoeing/Kayaking' ) },
	{ value: 'a8c.17.7', label: translate( 'Cheerleading' ) },
	{ value: 'a8c.17.8', label: translate( 'Climbing' ) },
	{ value: 'a8c.17.9', label: translate( 'Cricket' ) },
	{ value: 'a8c.17.10', label: translate( 'Figure Skating' ) },
	{ value: 'a8c.17.11', label: translate( 'Fly Fishing' ) },
	{ value: 'a8c.17.12', label: translate( 'Football' ) },
	{ value: 'a8c.17.13', label: translate( 'Freshwater Fishing' ) },
	{ value: 'a8c.17.14', label: translate( 'Game & Fish' ) },
	{ value: 'a8c.17.15', label: translate( 'Golf' ) },
	{ value: 'a8c.17.16', label: translate( 'Horse Racing' ) },
	{ value: 'a8c.17.17', label: translate( 'Horses' ) },
	{ value: 'a8c.17.18', label: translate( 'Hunting/Shooting' ) },
	{ value: 'a8c.17.19', label: translate( 'Inline Skating' ) },
	{ value: 'a8c.17.20', label: translate( 'Martial Arts' ) },
	{ value: 'a8c.17.21', label: translate( 'Mountain Biking' ) },
	{ value: 'a8c.17.22', label: translate( 'NASCAR Racing' ) },
	{ value: 'a8c.17.23', label: translate( 'Olympics' ) },
	{ value: 'a8c.17.24', label: translate( 'Paintball' ) },
	{ value: 'a8c.17.25', label: translate( 'Power & Motorcycles' ) },
	{ value: 'a8c.17.26', label: translate( 'Pro Basketball' ) },
	{ value: 'a8c.17.27', label: translate( 'Pro Ice Hockey' ) },
	{ value: 'a8c.17.28', label: translate( 'Rodeo' ) },
	{ value: 'a8c.17.29', label: translate( 'Rugby' ) },
	{ value: 'a8c.17.30', label: translate( 'Running/Jogging' ) },
	{ value: 'a8c.17.31', label: translate( 'Sailing' ) },
	{ value: 'a8c.17.32', label: translate( 'Saltwater Fishing' ) },
	{ value: 'a8c.17.33', label: translate( 'Scuba Diving' ) },
	{ value: 'a8c.17.34', label: translate( 'Skateboarding' ) },
	{ value: 'a8c.17.35', label: translate( 'Skiing' ) },
	{ value: 'a8c.17.36', label: translate( 'Snowboarding' ) },
	{ value: 'a8c.17.37', label: translate( 'Surfing/Bodyboarding' ) },
	{ value: 'a8c.17.38', label: translate( 'Swimming' ) },
	{ value: 'a8c.17.39', label: translate( 'Table Tennis/Ping-Pong' ) },
	{ value: 'a8c.17.40', label: translate( 'Tennis' ) },
	{ value: 'a8c.17.41', label: translate( 'Volleyball' ) },
	{ value: 'a8c.17.42', label: translate( 'Walking' ) },
	{ value: 'a8c.17.43', label: translate( 'Waterski/Wakeboard' ) },
	{ value: 'a8c.17.44', label: translate( 'Soccer' ), synonyms: translate( 'Football' ) },
	{ value: 'a8c.18', label: translate( 'Style & Fashion' ) },
	{ value: 'a8c.18.1', label: translate( 'Beauty' ) },
	{ value: 'a8c.18.2', label: translate( 'Body Art & Tattoos' ) },
	{ value: 'a8c.18.3', label: translate( 'Fashion' ) },
	{ value: 'a8c.18.4', label: translate( 'Jewelry' ) },
	{ value: 'a8c.18.5', label: translate( 'Clothing' ) },
	{ value: 'a8c.18.6', label: translate( 'Accessories' ) },
	{ value: 'a8c.19', label: translate( 'Technology & Computing' ) },
	{ value: 'a8c.19.1', label: translate( '3D Graphics' ) },
	{ value: 'a8c.19.2', label: translate( 'Animation' ) },
	{ value: 'a8c.19.3', label: translate( 'Antivirus Software' ) },
	{ value: 'a8c.19.4', label: translate( 'C/C++' ) },
	{ value: 'a8c.19.5', label: translate( 'Cameras & Camcorders' ) },
	{ value: 'a8c.19.6', label: translate( 'Smartphones & Cell Phones' ), synonyms: translate( 'Android, iPhone' ) },
	{ value: 'a8c.19.7', label: translate( 'Computer Certification' ) },
	{ value: 'a8c.19.8', label: translate( 'Computer Networking' ) },
	{ value: 'a8c.19.9', label: translate( 'Computer Peripherals' ) },
	{ value: 'a8c.19.10', label: translate( 'Computer & Tech Reviews' ) },
	{ value: 'a8c.19.11', label: translate( 'Data Centers' ) },
	{ value: 'a8c.19.12', label: translate( 'Databases' ) },
	{ value: 'a8c.19.13', label: translate( 'Desktop Publishing' ) },
	{ value: 'a8c.19.14', label: translate( 'Desktop Video' ) },
	{ value: 'a8c.19.15', label: translate( 'Email' ) },
	{ value: 'a8c.19.16', label: translate( 'Graphics Software' ) },
	{ value: 'a8c.19.17', label: translate( 'Home Video/DVD' ) },
	{ value: 'a8c.19.18', label: translate( 'Internet Technology' ) },
	{ value: 'a8c.19.19', label: translate( 'Java' ) },
	{ value: 'a8c.19.20', label: translate( 'JavaScript' ) },
	{ value: 'a8c.19.21', label: translate( 'Mac Support' ) },
	{ value: 'a8c.19.22', label: translate( 'MP3/MIDI' ) },
	{ value: 'a8c.19.23', label: translate( 'Net Conferencing' ) },
	{ value: 'a8c.19.24', label: translate( 'Internet for Beginners' ) },
	{ value: 'a8c.19.25', label: translate( 'Network Security' ) },
	{ value: 'a8c.19.26', label: translate( 'Palmtops/PDAs' ) },
	{ value: 'a8c.19.27', label: translate( 'PC Support' ) },
	{ value: 'a8c.19.28', label: translate( 'Tablets & Portable Computers' ) },
	{ value: 'a8c.19.29', label: translate( 'Entertainment' ) },
	{ value: 'a8c.19.30', label: translate( 'Shareware/Freeware' ) },
	{ value: 'a8c.19.31', label: translate( 'Unix' ) },
	{ value: 'a8c.19.32', label: translate( 'Visual Basic' ) },
	{ value: 'a8c.19.33', label: translate( 'Web Clip Art' ) },
	{ value: 'a8c.19.34', label: translate( 'Web Design/HTML' ) },
	{ value: 'a8c.19.35', label: translate( 'Web Search' ) },
	{ value: 'a8c.19.36', label: translate( 'Windows' ) },
	{ value: 'a8c.20', label: translate( 'Travel' ) },
	{ value: 'a8c.20.1', label: translate( 'Adventure Travel' ) },
	{ value: 'a8c.20.2', label: translate( 'Africa' ) },
	{ value: 'a8c.20.3', label: translate( 'Air Travel' ) },
	{ value: 'a8c.20.4', label: translate( 'Australia & New Zealand' ) },
	{ value: 'a8c.20.5', label: translate( 'Bed & Breakfasts' ) },
	{ value: 'a8c.20.6', label: translate( 'Budget Travel' ) },
	{ value: 'a8c.20.7', label: translate( 'Business Travel' ) },
	{ value: 'a8c.20.8', label: translate( 'By US Locale' ) },
	{ value: 'a8c.20.9', label: translate( 'Camping' ) },
	{ value: 'a8c.20.10', label: translate( 'Canada' ) },
	{ value: 'a8c.20.11', label: translate( 'Caribbean' ) },
	{ value: 'a8c.20.12', label: translate( 'Cruises' ) },
	{ value: 'a8c.20.13', label: translate( 'Eastern Europe' ) },
	{ value: 'a8c.20.14', label: translate( 'Europe' ) },
	{ value: 'a8c.20.15', label: translate( 'France' ) },
	{ value: 'a8c.20.16', label: translate( 'Greece' ) },
	{ value: 'a8c.20.17', label: translate( 'Honeymoons/Getaways' ) },
	{ value: 'a8c.20.18', label: translate( 'Hotels' ) },
	{ value: 'a8c.20.19', label: translate( 'Italy' ) },
	{ value: 'a8c.20.20', label: translate( 'Japan' ) },
	{ value: 'a8c.20.21', label: translate( 'Mexico & Central America' ) },
	{ value: 'a8c.20.22', label: translate( 'National Parks' ) },
	{ value: 'a8c.20.23', label: translate( 'South America' ) },
	{ value: 'a8c.20.24', label: translate( 'Spas' ) },
	{ value: 'a8c.20.25', label: translate( 'Theme Parks' ) },
	{ value: 'a8c.20.26', label: translate( 'Traveling with Kids' ) },
	{ value: 'a8c.20.27', label: translate( 'United Kingdom' ) },
	{ value: 'a8c.21', label: translate( 'Real Estate' ) },
	{ value: 'a8c.21.1', label: translate( 'Apartments' ) },
	{ value: 'a8c.21.2', label: translate( 'Architects' ) },
	{ value: 'a8c.21.3', label: translate( 'Buying/Selling Homes' ) },
	{ value: 'a8c.22', label: translate( 'Shopping' ) },
	{ value: 'a8c.22.1', label: translate( 'Contests & Freebies' ) },
	{ value: 'a8c.22.2', label: translate( 'Couponing' ) },
	{ value: 'a8c.22.3', label: translate( 'Product Comparison' ) },
	{ value: 'a8c.22.4', label: translate( 'Engines' ) },
	{ value: 'a8c.23', label: translate( 'Religion & Spirituality' ) },
	{ value: 'a8c.23.1', label: translate( 'Alternative Religions' ) },
	{ value: 'a8c.23.2', label: translate( 'Atheism/Agnosticism' ) },
	{ value: 'a8c.23.3', label: translate( 'Buddhism' ) },
	{ value: 'a8c.23.4', label: translate( 'Catholicism' ) },
	{ value: 'a8c.23.5', label: translate( 'Christianity' ) },
	{ value: 'a8c.23.6', label: translate( 'Hinduism' ) },
	{ value: 'a8c.23.7', label: translate( 'Islam' ) },
	{ value: 'a8c.23.8', label: translate( 'Judaism' ) },
	{ value: 'a8c.23.9', label: translate( 'Latter-Day Saints' ) },
	{ value: 'a8c.23.10', label: translate( 'Pagan/Wiccan' ) },
	{ value: 'a8c.24', label: translate( 'Uncategorized' ) },
]

/**
 * Shuffle a multi-dimensional array of verticals, but put the General vertical last.
 *
 * @param {Array} elements - the array of vertical elements to shuffle.
 * @returns {Array} the shuffled array of elements.
 */
function shuffleVerticals( elements ) {
	const newVerticals = shuffle( elements ).map( ( vertical ) => {
		if ( vertical.stepTwo ) {
			return Object.assign( {}, vertical, { stepTwo: shuffleVerticals( vertical.stepTwo ) } );
		}
		return vertical;
	} );
	const general = find( newVerticals, vertical => vertical.isGeneral );
	if ( general ) {
		newVerticals.splice( newVerticals.indexOf( general ), 1 );
		newVerticals.push( general );
	}
	return newVerticals;
}

export default {
	get() {
		switch ( abtest( 'signupSurveyStep' ) ) {
			case 'surveyStepV1': return shuffleVerticals( verticalsV1 );
			case 'surveyStepV2': return shuffleVerticals( verticalsV2 );
			default: throw new Error( 'Unknown variation' );
		}
	},

	getOther() {
		return verticalsOther;
	}
};
